name: Runs when pushed

on:
  push:
    branches:
      - main

jobs:
  actions:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Execute commands
        run: |
          echo "Hello"
          ls